version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
     POSTGRES_DB: gamedb
     POSTGRES_PASSWORD: 1
    restart: always
    ports:
      - 5432:5432
    expose: [5432]
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6380:6379'
    expose: [6380]
    volumes:
      - redisdata:/data

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
